env:
- namespace: "backstage"
  companyname: "HCA Rinse and Repeat Inc"
  gitopsnamespace: "janus-argocd"
  gitopsinfranamespace: "janus-infra-argocd"
  pipelinesnamespace: "janus-pipelines"
  vaultconfignamespace: "vault-config-operator"
  vaultnamespace: "vault"
  gitwebhooknamespace: "janus-gitwebhook-operator"
  janusinstancename: "janus-dev"
  githubinfraorganization: "ppremru-janus"
  githubinfrarevision: "main"
