{{- if .Values.namespaces }}
{{- range $index, $ns := .Values.namespaces }}
{{- if ne $index 0 }}
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: ""
    openshift.io/display-name: ""
  labels:
    kubernetes.io/metadata.name: {{ $ns }}
    openshift.io/cluster-monitoring: "true"
    build-namespace: ${{ns}}-build
    argocd.argoproj.io/managed-by: ${{ns}}-build
  name: {{ $ns }}
spec:
  finalizers:
  - kubernetes
{{- end }}
{{- end }}
{{- end }}
