apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pipelines-operator
  namespace: assemble-argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io  
spec:
  project: default
  source:
    repoURL: https://github.com/halkyonio/assemble-platforms.git
    targetRevision: HEAD
    path: charts/pipelines-operator
    helm:
      values: | 
        operator:
          channel: latest
          installPlanApproval: Automatic
          name: openshift-pipelines-operator-rh
          sourceName: redhat-operators
          sourceNamespace: openshift-marketplace
          startingCSV: openshift-pipelines-operator-rh.v1.8.0
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-operators
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
