{{- if .Values.oauth.enabled }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'openshift-config-default-cluster-admin'
  labels:
    {{- include "assemble-backstage.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: default
    namespace: openshift-config
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'cluster-admin'
{{- end }}
